[package]
name = "clipper"
version = "4.6.2"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
# build = "src/build.rs"

[dependencies]

[build-dependencies]
bindgen = { git = "https://github.com/rust-lang-nursery/rust-bindgen" }
